import { Product, User, Order, WalletTransaction, NotificationItem } from './types'

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`

export const INITIAL_USER: User = {
  id: 'usr_curr_101',
  name: 'Ananya Deshmukh',
  email: 'ananya.d@rewear.org',
  phone: '+91 98765 43210',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  location: 'Kothrud, Pune',
  memberSince: 'March 2024',
  rating: 4.9,
  ratingCount: 28,
  successfulExchanges: 14,
  donationsCompleted: 6,
  itemsListed: 8,
  pointsBalance: 1250,
  lockedPoints: 750,
  badges: ['Eco Pioneer', 'Verified Swapper', 'Top Seller', 'Green Donor'],
}

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    title: "Levi's Classic Trucker Denim Jacket",
    brand: "Levi's",
    category: 'Jackets',
    size: 'M',
    gender: 'Unisex',
    condition: 'Like New',
    defects: [],
    points: 750,
    distance: '1.2 km',
    distanceKm: 1.2,
    seller: {
      id: 'usr_201',
      name: 'Riya Shah',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
      rating: 4.9,
      location: 'Kothrud, Pune',
      exchangesCount: 18,
      joinedDate: 'Jan 2024',
    },
    images: [
      img('photo-1576871337622-98d48d1cf531'),
      img('photo-1544441893-675973e31985'),
    ],
    description: "Authentic Levi's rigid denim jacket in dark indigo blue. Worn only twice, preserved in pristine condition. Zero fading or fraying.",
    pickupType: 'both',
    createdAt: '2 hours ago',
    status: 'active',
  },
  {
    id: 2,
    title: 'Zara Floral Summer Midi Dress',
    brand: 'Zara',
    category: 'Dresses',
    size: 'S',
    gender: 'Women',
    condition: 'Excellent',
    defects: ['Minor thread pull at back hem'],
    points: 600,
    distance: '2.4 km',
    distanceKm: 2.4,
    seller: {
      id: 'usr_202',
      name: 'Pooja Kulkarni',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
      rating: 4.8,
      location: 'Kalyani Nagar, Pune',
      exchangesCount: 12,
      joinedDate: 'Nov 2023',
    },
    images: [
      img('photo-1595777457583-95e059d581b8'),
      img('photo-1618932260643-eee4a2f652a6'),
    ],
    description: 'Breezy lightweight viscose midi dress from Zara. Perfect for summer afternoon outings. Disclosed thread pull at inner hemline.',
    pickupType: 'both',
    createdAt: '5 hours ago',
    status: 'active',
  },
  {
    id: 3,
    title: 'Nike Pegasus 39 Running Shoes',
    brand: 'Nike',
    category: 'Shoes',
    size: 'UK 7',
    gender: 'Unisex',
    condition: 'Good',
    defects: ['Slight outsole wear', 'Minor scuff on left toe cap'],
    points: 900,
    distance: '3.1 km',
    distanceKm: 3.1,
    seller: {
      id: 'usr_203',
      name: 'Aditya Rao',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      rating: 4.7,
      location: 'Viman Nagar, Pune',
      exchangesCount: 22,
      joinedDate: 'Feb 2024',
    },
    images: [
      img('photo-1542291026-7eec264c27ff'),
      img('photo-1552346154-21d32810aba3'),
    ],
    description: 'High performance Nike Pegasus daily trainers. Air Zoom unit intact with high energy return. Washed & sanitized prior to listing.',
    pickupType: 'both',
    createdAt: '1 day ago',
    status: 'active',
  },
  {
    id: 4,
    title: 'H&M Oversized Heavyweight Cotton T-Shirt',
    brand: 'H&M',
    category: 'T-Shirts',
    size: 'L',
    gender: 'Unisex',
    condition: 'Like New',
    defects: [],
    points: 350,
    distance: '1.8 km',
    distanceKm: 1.8,
    seller: {
      id: 'usr_204',
      name: 'Sneha Bapat',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      rating: 4.9,
      location: 'Baner, Pune',
      exchangesCount: 15,
      joinedDate: 'Apr 2024',
    },
    images: [
      img('photo-1521572163474-6864f9cf17ab'),
    ],
    description: 'Minimalist sage green relaxed fit t-shirt in 240 GSM organic cotton. Extremely comfortable streetwear basic.',
    pickupType: 'meetup',
    createdAt: '3 hours ago',
    status: 'active',
  },
  {
    id: 5,
    title: 'Adidas Fleece Essential Pullover Hoodie',
    brand: 'Adidas',
    category: 'Hoodies',
    size: 'M',
    gender: 'Men',
    condition: 'Excellent',
    defects: [],
    points: 800,
    distance: '4.2 km',
    distanceKm: 4.2,
    seller: {
      id: 'usr_205',
      name: 'Kabir Patil',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      rating: 4.6,
      location: 'Aundh, Pune',
      exchangesCount: 9,
      joinedDate: 'Dec 2023',
    },
    images: [
      img('photo-1556821840-3a63f95609a7'),
    ],
    description: 'Cozy cotton-blend fleece hoodie featuring embroidered Adidas trefoil logo. Drawstring hood and front kangaroo pocket.',
    pickupType: 'both',
    createdAt: '2 days ago',
    status: 'active',
  },
  {
    id: 6,
    title: 'Uniqlo Premium Linen Long Sleeve Shirt',
    brand: 'Uniqlo',
    category: 'Shirts',
    size: 'M',
    gender: 'Men',
    condition: 'Good',
    defects: ['Subtle collar crease'],
    points: 500,
    distance: '2.1 km',
    distanceKm: 2.1,
    seller: {
      id: 'usr_206',
      name: 'Varun Menon',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
      rating: 4.8,
      location: 'Wakad, Pune',
      exchangesCount: 31,
      joinedDate: 'Oct 2023',
    },
    images: [
      img('photo-1603252110481-7ba873bf42ab'),
    ],
    description: '100% French linen breathable shirt in crisp white. Softened through eco washes. Great casual summer workwear item.',
    pickupType: 'both',
    createdAt: '1 day ago',
    status: 'active',
  },
  {
    id: 7,
    title: 'Mango Tailored Linen Blend Trousers',
    brand: 'Mango',
    category: 'Jeans',
    size: 'S',
    gender: 'Women',
    condition: 'Excellent',
    defects: [],
    points: 650,
    distance: '2.9 km',
    distanceKm: 2.9,
    seller: {
      id: 'usr_207',
      name: 'Ishita Nair',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
      rating: 4.9,
      location: 'Hinjewadi, Pune',
      exchangesCount: 14,
      joinedDate: 'Jan 2024',
    },
    images: [
      img('photo-1506629905607-d9f297d1d8d2'),
    ],
    description: 'High-waisted wide leg trousers in oat beige. Comes with matching fabric belt and deep side pockets.',
    pickupType: 'delivery',
    createdAt: '4 days ago',
    status: 'active',
  },
  {
    id: 8,
    title: 'Vintage Oversized Heavy Corduroy Shacket',
    brand: 'Thrift Vintage',
    category: 'Jackets',
    size: 'L',
    gender: 'Unisex',
    condition: 'Good',
    defects: ['Natural vintage patina on copper buttons'],
    points: 700,
    distance: '1.5 km',
    distanceKm: 1.5,
    seller: {
      id: 'usr_208',
      name: 'Arjun Sethi',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
      rating: 4.7,
      location: 'Deccan, Pune',
      exchangesCount: 26,
      joinedDate: 'Aug 2023',
    },
    images: [
      img('photo-1591047139829-d91aecb6caea'),
    ],
    description: 'Retro 90s corduroy shirt jacket in rust terracotta tone. Thick ribbed texture with warm brushed interior.',
    pickupType: 'both',
    createdAt: '6 hours ago',
    status: 'active',
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-98421',
    product: INITIAL_PRODUCTS[0], // Levi's Denim Jacket (750 pts)
    type: 'meetup',
    points: 750,
    counterparty: {
      name: 'Riya Shah',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
      role: 'seller',
      rating: 4.9,
      phone: '+91 98220 11223',
    },
    status: 'active',
    stage: 'Meetup/Delivery Set',
    stageIndex: 2,
    meetupDetails: {
      locationName: 'FC Road Starbucks / Goodluck Cafe Junction',
      address: 'Deccan Gymkhana, FC Road, Pune',
      date: 'Tomorrow, 5:30 PM',
      time: '17:30',
      isConfirmed: true,
    },
    createdAt: 'Today at 10:15 AM',
  },
  {
    id: 'ORD-77103',
    product: INITIAL_PRODUCTS[1], // Zara Dress
    type: 'delivery',
    points: 600,
    counterparty: {
      name: 'Pooja Kulkarni',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
      role: 'seller',
      rating: 4.8,
      phone: '+91 97654 88120',
    },
    status: 'active',
    stage: 'Points Locked',
    stageIndex: 1,
    deliveryDetails: {
      totalFee: 120,
      buyerShare: 60,
      sellerShare: 60,
      trackingNumber: 'RW-DEL-884920',
      carrier: 'Dunzo Eco Express',
      status: 'Courier assigned for pickup',
    },
    createdAt: 'Yesterday',
  },
  {
    id: 'ORD-44910',
    product: INITIAL_PRODUCTS[3], // H&M T-Shirt
    type: 'meetup',
    points: 350,
    counterparty: {
      name: 'Sneha Bapat',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      role: 'buyer',
      rating: 4.9,
      phone: '+91 99112 33445',
    },
    status: 'completed',
    stage: 'Completed',
    stageIndex: 5,
    meetupDetails: {
      locationName: 'Westend Mall Entrance, Aundh',
      address: 'Aundh Road, Pune',
      date: '28 Aug 2026',
      time: '16:00',
      isConfirmed: true,
    },
    createdAt: '28 Aug 2026',
  },
]

export const MOCK_WALLET_TRANSACTIONS: WalletTransaction[] = [
  {
    id: 'TX-901',
    title: "Escrow Hold: Levi's Denim Jacket",
    date: '02 Sep 2026',
    points: 750,
    type: 'locked',
    status: 'Pending Escrow',
    orderId: 'ORD-98421',
    details: 'Points locked safely in ReWear Escrow until item handoff is verified by buyer.',
    counterpartyName: 'Riya Shah',
  },
  {
    id: 'TX-899',
    title: 'Garment Listed & Swapped: H&M Oversized Tee',
    date: '28 Aug 2026',
    points: 350,
    type: 'earned',
    status: 'Completed',
    orderId: 'ORD-44910',
    details: 'Points released to your wallet following successful nearby meetup completion.',
    counterpartyName: 'Sneha Bapat',
  },
  {
    id: 'TX-850',
    title: 'Donation Reward: 3 Cotton Shirts to Goonj NGO',
    date: '20 Aug 2026',
    points: 400,
    type: 'earned',
    status: 'Completed',
    details: 'Reward bonus granted for verified NGO wardrobe donation drop-off.',
    counterpartyName: 'Goonj NGO',
  },
  {
    id: 'TX-812',
    title: 'Exchange Completed: Nike Pegasus Shoes',
    date: '15 Aug 2026',
    points: 900,
    type: 'spent',
    status: 'Completed',
    details: 'Spent points for high performance running shoes delivered via Dunzo Eco Express.',
    counterpartyName: 'Aditya Rao',
  },
  {
    id: 'TX-750',
    title: 'Welcome Bonus: Profile Verification',
    date: '01 Mar 2024',
    points: 500,
    type: 'earned',
    status: 'Completed',
    details: 'Bonus points awarded for completing profile verification & Pune location pin.',
  },
]

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    title: 'Meetup Confirmed!',
    message: 'Riya Shah confirmed the meetup spot at FC Road Starbucks for tomorrow, 5:30 PM.',
    time: '10 mins ago',
    read: false,
    type: 'order',
    orderId: 'ORD-98421',
  },
  {
    id: 'notif_2',
    title: 'Points Locked in Escrow',
    message: '750 ReWear Points have been temporarily held for Order #ORD-98421.',
    time: '2 hours ago',
    read: false,
    type: 'points',
    orderId: 'ORD-98421',
  },
  {
    id: 'notif_3',
    title: 'Listing Approved & Published',
    message: 'Your valuation for Cotton Co-ord set (750 Points) was approved and published live!',
    time: 'Yesterday',
    read: true,
    type: 'system',
  },
  {
    id: 'notif_4',
    title: 'Delivery Courier Dispatched',
    message: 'Dunzo Eco Courier #RW-DEL-884920 picked up Zara Midi Dress from Pooja Kulkarni.',
    time: 'Yesterday',
    read: true,
    type: 'order',
    orderId: 'ORD-77103',
  },
  {
    id: 'notif_5',
    title: 'Rating Requested',
    message: 'Please rate your recent swap experience with Sneha Bapat for Order #ORD-44910.',
    time: '3 days ago',
    read: true,
    type: 'system',
    orderId: 'ORD-44910',
  },
  {
    id: 'notif_6',
    title: 'Saved Favorite Update',
    message: 'Nike Pegasus 39 Running Shoes is now available for nearby meetup in Viman Nagar!',
    time: '4 days ago',
    read: true,
    type: 'favorite',
  },
]

export const MOCK_CHAT_THREADS: import('./types').ChatThread[] = [
  {
    id: 'chat_1',
    orderId: 'ORD-98421',
    productTitle: "Levi's Classic Trucker Denim Jacket",
    productImage: 'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=400&q=80',
    counterparty: {
      id: 'usr_201',
      name: 'Riya Shah',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
      rating: 4.9,
    },
    lastMessage: 'Awesome, see you near the main entrance table.',
    lastMessageTime: '10:20 AM',
    unreadCount: 1,
    messages: [
      { id: 'msg_1', senderId: 'usr_201', senderName: 'Riya Shah', text: 'Hi Ananya! Is 5:30 PM tomorrow good for meeting at FC Road Starbucks?', time: '10:15 AM', isMine: false },
      { id: 'msg_2', senderId: 'usr_curr_101', senderName: 'You', text: 'Yes, 5:30 PM works great for me! I will carry the denim jacket in clean paper packaging.', time: '10:18 AM', isMine: true },
      { id: 'msg_3', senderId: 'usr_201', senderName: 'Riya Shah', text: 'Awesome, see you near the main entrance table.', time: '10:20 AM', isMine: false },
    ],
  },
  {
    id: 'chat_2',
    orderId: 'ORD-77103',
    productTitle: 'Zara Floral Summer Midi Dress',
    productImage: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=400&q=80',
    counterparty: {
      id: 'usr_202',
      name: 'Pooja Kulkarni',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
      rating: 4.8,
    },
    lastMessage: 'I have handed over the package to Dunzo delivery partner!',
    lastMessageTime: 'Yesterday',
    unreadCount: 0,
    messages: [
      { id: 'msg_201', senderId: 'usr_202', senderName: 'Pooja Kulkarni', text: 'Hi! I packed the dress with extra care.', time: 'Yesterday 3:00 PM', isMine: false },
      { id: 'msg_202', senderId: 'usr_curr_101', senderName: 'You', text: 'Thanks Pooja! Tracking link shows courier assigned.', time: 'Yesterday 3:15 PM', isMine: true },
      { id: 'msg_203', senderId: 'usr_202', senderName: 'Pooja Kulkarni', text: 'I have handed over the package to Dunzo delivery partner!', time: 'Yesterday 4:00 PM', isMine: false },
    ],
  },
]

